# Generated by Django 6.1 on 2026-09-05 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_role_from_is_staff(apps, schema_editor):
    """Existing accounts predate the role field: staff become admins, everyone
    else stays on the `member` default. Without this every current admin would
    silently lose access to the admin portal."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_staff=True).update(role="admin")


def set_is_staff_from_role(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="admin").update(is_staff=True)
    User.objects.exclude(role="admin").update(is_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('trainer', 'Trainer'), ('admin', 'Admin')], default='member', max_length=10),
        ),
        migrations.RunPython(set_role_from_is_staff, set_is_staff_from_role),
    ]
