# Generated by Django 6.1 on 2026-09-05 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_memberprofile_trainer_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Standing height in centimetres, used for BMI.', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
