# Generated by Django 6.1 on 2026-09-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_memberprofile_height_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
