# Generated by Django 6.1 on 2026-09-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_memberprofile_biometric_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
