# Generated by Django 6.1 on 2026-10-08 16:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mfa_device_and_recovery_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('normal', 'Normal'), ('remember', 'Remember me'), ('trusted', 'Trusted device')], default='normal', max_length=10)),
                ('secret_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('current_jti', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='accounts_au_user_id_482cc7_idx')],
            },
        ),
    ]
