# Generated by Django 6.1 on 2026-09-06 12:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('label', models.CharField(blank=True, help_text='e.g. Training day, Rest day.', max_length=60)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('grain', 'Grains & cereals'), ('protein', 'Protein'), ('dairy', 'Dairy'), ('vegetable', 'Vegetables'), ('fruit', 'Fruit'), ('fat', 'Fats & oils'), ('supplement', 'Supplements'), ('other', 'Other')], default='other', max_length=12)),
                ('calories', models.DecimalField(decimal_places=2, help_text='kcal per 100g', max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('serving_label', models.CharField(blank=True, help_text='e.g. 1 roti, 1 cup, 1 scoop.', max_length=40)),
                ('serving_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Grams in one serving.', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DietMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('snack_am', 'Mid-morning snack'), ('lunch', 'Lunch'), ('snack_pm', 'Evening snack'), ('dinner', 'Dinner'), ('pre_workout', 'Pre-workout'), ('post_workout', 'Post-workout')], max_length=14)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.dietday')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My diet plan', max_length=100)),
                ('goal', models.CharField(choices=[('cut', 'Fat loss'), ('maintain', 'Maintenance'), ('bulk', 'Muscle gain')], default='maintain', max_length=10)),
                ('target_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('target_protein_g', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_plans_written', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='dietday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='nutrition.dietplan'),
        ),
        migrations.CreateModel(
            name='DietMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.dietmeal')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_items', to='nutrition.fooditem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dietplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='one_active_diet_plan_per_user'),
        ),
        migrations.AddConstraint(
            model_name='dietday',
            constraint=models.UniqueConstraint(fields=('plan', 'weekday'), name='one_diet_day_per_weekday'),
        ),
    ]
