# Generated by Django 6.1 on 2026-09-06 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shown in the header and on invoices.', max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('accent', models.CharField(default='#ff3d5a', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Use a hex colour like #ff3d5a.')])),
                ('accent_2', models.CharField(default='#ffb020', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Use a hex colour like #ff3d5a.')])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Printed on invoices.')),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, help_text='For CGST/SGST vs IGST.', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'branding',
                'ordering': ['-is_active', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_branding')],
            },
        ),
    ]
