# Generated by Django 6.1 on 2026-09-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_branding_organisation'),
        ('tenancy', '0002_backfill_the_founding_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branding',
            name='one_active_branding',
        ),
        migrations.AddConstraint(
            model_name='branding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organisation', 'is_active'), name='one_active_branding_per_organisation'),
        ),
    ]
