# Generated by Django 6.1 on 2026-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_alter_branding_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='display_font',
            field=models.CharField(choices=[('Bebas Neue', 'Bebas Neue - condensed, athletic (default)'), ('Anton', 'Anton - heavy and blunt'), ('Oswald', 'Oswald - condensed, quieter'), ('Archivo Black', 'Archivo Black - very heavy'), ('Teko', 'Teko - squared, sporty')], default='Bebas Neue', help_text='Headline font. Body text is always Inter, for legibility.', max_length=20),
        ),
    ]
