# Generated by Django 6.1 on 2026-09-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0005_branding_display_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='opening_hours',
            field=models.TextField(blank=True, help_text="One line per row, e.g. 'Monday to Friday: 5:30 - 23:00'."),
        ),
        migrations.AlterField(
            model_name='branding',
            name='address',
            field=models.TextField(blank=True, help_text='Printed on invoices and shown on the website.'),
        ),
    ]
