# Generated by Django 6.1 on 2026-09-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expiry_soon', 'Membership expiring soon'), ('expired', 'Membership expired'), ('payment_due', 'Payment reminder'), ('welcome', 'Welcome')], max_length=20)),
                ('subject_date', models.DateField()),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['kind', '-sent_at'], name='notificatio_kind_7ddb1c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'subject_date'), name='one_notification_per_subject')],
            },
        ),
    ]
