# Generated by Django 6.1 on 2026-09-06 11:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('flat', 'Flat amount off')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='A percentage (0-100) or a flat amount, depending on the type.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, help_text='Blank = no end date.', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited.', null=True)),
                ('max_uses_per_member', models.PositiveIntegerField(default=1, help_text='0 = unlimited per member.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plans', models.ManyToManyField(blank=True, related_name='discounts', to='billing.plan')),
            ],
            options={
                'ordering': ['-is_active', 'code'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.discount'),
        ),
    ]
