# Generated by Django 6.1 on 2026-09-07 09:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymentorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('valid_on', models.DateField(default=django.utils.timezone.localdate, help_text='The single day this pass is good for.')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank transfer'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_passes_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid_on', '-id'],
                'indexes': [models.Index(fields=['valid_on'], name='billing_day_valid_o_e35fa5_idx')],
            },
        ),
    ]
