# Generated by Django 6.1 on 2026-09-06 12:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_payment_discount_amount_discount_payment_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('percent', 'Percentage of the payment'), ('flat', 'Flat amount per payment')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, help_text='Blank applies the rule to every plan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='billing.plan')),
                ('trainer', models.ForeignKey(blank=True, help_text='Blank applies the rule to every trainer.', limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('percent', 'Percentage of the payment'), ('flat', 'Flat amount per payment')], max_length=10)),
                ('rate_applied', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid out'), ('void', 'Void')], default='pending', max_length=10)),
                ('earned_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entry', to='billing.payment')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='commissions.commissionrule')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='commissions.payout')),
            ],
            options={
                'verbose_name_plural': 'commission entries',
                'ordering': ['-earned_on', '-id'],
                'indexes': [models.Index(fields=['trainer', 'status'], name='commissions_trainer_42b283_idx')],
            },
        ),
    ]
