# Generated by Django 6.1 on 2026-08-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("bio", models.TextField(blank=True)),
                ("specialty", models.CharField(blank=True, max_length=150)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="instructor_photos/"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
