# Generated by Django 6.1 on 2026-09-05 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='booked', max_length=10)),
                ('position', models.PositiveIntegerField(blank=True, help_text='Place in the waitlist queue; null once booked.', null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedule_app.classsession')),
            ],
            options={
                'ordering': ['position', 'booked_at'],
                'constraints': [models.UniqueConstraint(fields=('member', 'session'), name='one_booking_per_member_per_class')],
            },
        ),
    ]
