"""Registering a gym's sending domain with the email provider.

The DKIM public key is *generated by the provider*, per domain. It cannot be
computed here and it cannot be guessed, so an install with no provider
credentials genuinely cannot produce the records a gym needs to publish. This
module is therefore split the same way certificates are: a real adapter, and an
honest one that says it has nothing rather than inventing something.

Postmark is the implemented provider. Its domains API returns the DKIM selector
and value and a return-path CNAME in one call, which is what makes a guided
setup screen possible -- an owner is shown three exact rows to paste, not sent
to read someone's documentation.
"""

import logging

from django.conf import settings

logger = logging.getLogger(__name__)


class Provider:
    name = "none"
    #: What a gym adds to their SPF record to authorise this provider.
    spf_include = ""

    @property
    def configured(self):
        return False

    def register(self, identity):
        """Create the domain with the provider and fill in its DNS records."""
        raise NotImplementedError


class ManualProvider(Provider):
    """No credentials configured, so no records can be issued.

    Says so plainly. The alternative -- showing a plausible-looking DKIM record
    that no provider will ever sign with -- would have an owner edit their DNS,
    wait, and be told it failed, with nothing to fix.
    """

    name = "manual"
    spf_include = "spf.mtasv.net"

    def register(self, identity):
        from .email_identity import SendingSetupError

        raise SendingSetupError(
            "No email provider is configured on this platform yet, so the DKIM "
            "record cannot be issued. Ask your administrator to connect one."
        )


class PostmarkProvider(Provider):
    name = "postmark"
    spf_include = "spf.mtasv.net"
    BASE = "https://api.postmarkapp.com"

    def __init__(self, token):
        self.token = token

    @property
    def configured(self):
        return bool(self.token)

    def _headers(self):
        return {
            "X-Postmark-Account-Token": self.token,
            "Accept": "application/json",
            "Content-Type": "application/json",
        }

    def register(self, identity):
        import requests

        from .email_identity import SendingSetupError

        try:
            response = requests.post(
                f"{self.BASE}/domains",
                json={"Name": identity.domain},
                headers=self._headers(),
                timeout=15,
            )
        except requests.RequestException as exc:
            logger.warning("Postmark domain creation failed: %s", exc)
            raise SendingSetupError("Could not reach the email provider.")

        if response.status_code == 422:
            # Already registered on the account, which is a success for us --
            # fetch it instead so a retry is not a dead end.
            existing = self._find(identity.domain)
            if existing is None:
                raise SendingSetupError(response.json().get("Message", "Refused."))
            data = existing
        elif response.status_code not in (200, 201):
            logger.warning(
                "Postmark refused %s: %s %s",
                identity.domain, response.status_code, response.text[:200],
            )
            raise SendingSetupError("The email provider refused that domain.")
        else:
            data = response.json()

        identity.dkim_selector = data.get("DKIMPendingHost", "").split("._domainkey")[0]
        identity.dkim_value = data.get("DKIMPendingTextValue", "") or data.get(
            "DKIMTextValue", ""
        )
        identity.return_path_cname = data.get("ReturnPathDomainCNAMEValue", "")
        identity.save(
            update_fields=["dkim_selector", "dkim_value", "return_path_cname"]
        )
        return identity

    def _find(self, domain):
        import requests

        try:
            response = requests.get(
                f"{self.BASE}/domains", headers=self._headers(), timeout=15
            )
            for entry in response.json().get("Domains", []):
                if entry.get("Name", "").lower() == domain.lower():
                    detail = requests.get(
                        f"{self.BASE}/domains/{entry['ID']}",
                        headers=self._headers(),
                        timeout=15,
                    )
                    return detail.json()
        except (requests.RequestException, ValueError, KeyError):
            logger.warning("Could not look up %s at Postmark", domain, exc_info=True)
        return None


def provider():
    token = getattr(settings, "POSTMARK_ACCOUNT_TOKEN", "")
    if token:
        return PostmarkProvider(token)
    return ManualProvider()
