# Generated by Django 6.1 on 2026-09-06 12:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_payment_discount_amount_discount_payment_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-financial_year'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('financial_year', models.CharField(max_length=9)),
                ('sequence', models.PositiveIntegerField()),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('seller_gstin', models.CharField(blank=True, max_length=15)),
                ('buyer_gstin', models.CharField(blank=True, max_length=15)),
                ('place_of_supply', models.CharField(blank=True, max_length=60)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=5)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='billing.payment')),
            ],
            options={
                'ordering': ['-issued_on', '-sequence'],
            },
        ),
    ]
