# Generated by Django 6.1 on 2026-09-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_discount_code_alter_plan_name_and_more'),
        ('invoicing', '0002_invoice_tenant_invoicecounter_tenant'),
        ('tenancy', '0002_backfill_the_founding_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='invoicecounter',
            name='financial_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='one_invoice_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='invoicecounter',
            constraint=models.UniqueConstraint(fields=('tenant', 'financial_year'), name='one_counter_per_tenant_per_year'),
        ),
    ]
