# Generated by Django 6.1 on 2026-09-06 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('follow_up_on', models.DateField(help_text='The day to call them back.')),
                ('status', models.CharField(choices=[('open', 'To call'), ('contacted', 'Contacted'), ('joined', 'Joined'), ('lost', 'Not interested')], default='open', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('last_contacted_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['follow_up_on', '-created_at'],
                'indexes': [models.Index(fields=['status', 'follow_up_on'], name='crm_enquiry_status_18a4f1_idx')],
            },
        ),
    ]
