# Generated by Django 6.1 on 2026-09-06 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_discount_amount_discount_payment_discount'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='converted_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_enquiry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='interested_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='source',
            field=models.CharField(choices=[('walk_in', 'Walked in'), ('phone', 'Phone call'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google', 'Google / search'), ('referral', 'Member referral'), ('other', 'Other')], default='walk_in', max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('open', 'To call'), ('contacted', 'Contacted'), ('trial', 'Trial booked'), ('joined', 'Joined'), ('lost', 'Not interested')], default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='EnquiryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_notes', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail', to='crm.enquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
