# Generated by Django 6.1 on 2026-09-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_enquiry_assigned_to_enquiry_converted_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiet_days', models.PositiveSmallIntegerField(default=10, help_text='No check-in for this many days and a member is worth a call.')),
                ('cooling_days', models.PositiveSmallIntegerField(default=5, help_text='Fewer days than this and the member is fine.')),
                ('grace_days', models.PositiveSmallIntegerField(default=7, help_text='New members are left alone for this many days.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'retention policies',
                'ordering': ['-is_active', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_retention_policy'), models.CheckConstraint(condition=models.Q(('cooling_days__lt', models.F('quiet_days'))), name='cooling_before_quiet')],
            },
        ),
    ]
