# Generated by Django 6.1 on 2026-09-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_enquiry_tenant_enquirynote_tenant_and_more'),
        ('tenancy', '0002_backfill_the_founding_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retentionpolicy',
            name='one_active_retention_policy',
        ),
        migrations.AddConstraint(
            model_name='retentionpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organisation', 'is_active'), name='one_active_retention_policy_per_organisation'),
        ),
    ]
