# Generated by Django 6.1 on 2026-09-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_enquiry_tenant_alter_enquirynote_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='source',
            field=models.CharField(choices=[('walk_in', 'Walked in'), ('phone', 'Phone call'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google', 'Google / search'), ('referral', 'Member referral'), ('website', 'Gym website'), ('other', 'Other')], default='walk_in', max_length=10),
        ),
    ]
