# Generated by Django 6.1 on 2026-09-05 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_checkinout_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('api_key_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_id', models.CharField(max_length=64)),
                ('event_time', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('unmatched', 'No matching member'), ('duplicate', 'Duplicate punch'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to='attendance.checkinout')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_time', '-id'],
                'constraints': [models.UniqueConstraint(fields=('device', 'biometric_id', 'event_time'), name='one_punch_per_device_time')],
            },
        ),
    ]
