# Generated by Django 6.1 on 2026-09-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='grace_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Days after expiry a lapsed member may still enter.'),
        ),
        migrations.AddField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[('terminal', 'Attendance terminal'), ('turnstile', 'Turnstile'), ('door', 'Door lock')], default='terminal', max_length=10),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('unmatched', 'No matching member'), ('duplicate', 'Duplicate punch'), ('denied', 'Refused entry'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
    ]
