# Generated by Django 6.1 on 2026-09-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='method',
            field=models.CharField(choices=[('tap', 'Self-service tap'), ('qr', 'QR scan'), ('biometric', 'Biometric device'), ('manual', 'Added by staff')], default='tap', max_length=10),
        ),
    ]
