# Generated by Django 6.1 on 2026-09-07 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_checkinout_method'),
        ('billing', '0004_daypass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='day_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='billing.daypass'),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='checkinout',
            constraint=models.UniqueConstraint(condition=models.Q(('check_out_time__isnull', True)), fields=('day_pass',), name='one_open_checkin_per_day_pass'),
        ),
        migrations.AddConstraint(
            model_name='checkinout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('day_pass__isnull', True), ('user__isnull', False)), models.Q(('day_pass__isnull', False), ('user__isnull', True)), _connector='OR'), name='visit_belongs_to_member_or_guest'),
        ),
    ]
