# Generated by Django 6.1 on 2026-09-09 08:43

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, storage=core.storage.private_media_storage, upload_to='receipts/'),
        ),
    ]
