# Generated by Django 6.1 on 2026-08-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_exercisevideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Sub-muscle group within muscle_group, e.g. 'Upper Chest'.",
                max_length=60,
            ),
        ),
    ]
