# Generated by Django 6.1 on 2026-09-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_backfill_training_data'),
        ('workouts', '0005_workoutlog_tenant_workoutsession_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
    ]
