# Generated by Django 6.1 on 2026-09-07 05:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0004_splitday_splitexercise_workoutsplit_splitday_split_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable id, e.g. 'first-50-visits'.", unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum'), (5, 'Elite')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('criterion', models.CharField(choices=[('visits', 'Total gym visits'), ('streak', 'Longest daily streak'), ('workouts', 'Workout sessions logged'), ('sets', 'Sets logged'), ('records', 'Personal records set'), ('months', 'Months as a member')], max_length=10)),
                ('threshold', models.PositiveIntegerField(help_text='The number that has to be reached for this badge.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['criterion', 'threshold'],
                'constraints': [models.UniqueConstraint(fields=('criterion', 'threshold'), name='one_badge_per_criterion_threshold')],
            },
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_opt_in', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('value_at_award', models.PositiveIntegerField(default=0)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='gamification.badge')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_on', '-id'],
                'constraints': [models.UniqueConstraint(fields=('member', 'badge'), name='one_award_per_badge')],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reps', models.PositiveIntegerField()),
                ('bodyweight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('achieved_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='workouts.exercise')),
                ('log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='workouts.workoutlog')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_on', '-weight_kg'],
                'indexes': [models.Index(fields=['exercise', '-achieved_on'], name='gamificatio_exercis_f5162d_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'exercise', 'achieved_on'), name='one_record_per_exercise_per_day')],
            },
        ),
    ]
