# Generated by Django 6.1 on 2026-09-07 12:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        ('workouts', '0004_splitday_splitexercise_workoutsplit_splitday_split_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='badge',
            name='one_badge_per_criterion_threshold',
        ),
        migrations.AddField(
            model_name='badge',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='criterion',
            field=models.CharField(choices=[('visits', 'Total gym visits'), ('streak', 'Longest daily streak'), ('workouts', 'Workout sessions logged'), ('sets', 'Sets logged'), ('records', 'Personal records set'), ('months', 'Months as a member'), ('classes', 'Classes attended'), ('month_streak', 'Consecutive months trained'), ('lift', 'Heaviest lift on one exercise (kg)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='badge',
            name='threshold',
            field=models.PositiveIntegerField(help_text='The number to reach: a count, or kilograms for a lift badge.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(condition=models.Q(('criterion', 'lift'), _negated=True), fields=('criterion', 'threshold'), name='one_badge_per_criterion_threshold'),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(condition=models.Q(('criterion', 'lift')), fields=('exercise', 'threshold'), name='one_lift_badge_per_exercise_weight'),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('criterion', 'lift'), ('exercise__isnull', False)), models.Q(models.Q(('criterion', 'lift'), _negated=True), ('exercise__isnull', True)), _connector='OR'), name='only_lift_badges_name_an_exercise'),
        ),
    ]
