# Generated by Django 6.1 on 2026-09-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_badge_organisation'),
        ('tenancy', '0002_backfill_the_founding_tenant'),
        ('workouts', '0004_splitday_splitexercise_workoutsplit_splitday_split_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='badge',
            name='one_badge_per_criterion_threshold',
        ),
        migrations.RemoveConstraint(
            model_name='badge',
            name='one_lift_badge_per_exercise_weight',
        ),
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.SlugField(help_text="Stable id, e.g. 'first-50-visits'."),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(fields=('organisation', 'code'), name='one_badge_code_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(condition=models.Q(('criterion', 'lift'), _negated=True), fields=('organisation', 'criterion', 'threshold'), name='one_badge_per_criterion_threshold'),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(condition=models.Q(('criterion', 'lift')), fields=('organisation', 'exercise', 'threshold'), name='one_lift_badge_per_exercise_weight'),
        ),
    ]
