# Generated by Django 6.1 on 2026-09-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_remove_badge_one_badge_per_criterion_threshold_and_more'),
        ('tenancy', '0002_backfill_the_founding_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbadge',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
    ]
