# Generated by Django 6.1 on 2026-09-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_memberbadge_tenant_personalrecord_tenant'),
        ('tenancy', '0003_backfill_training_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='memberbadge',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
    ]
