# Generated by Django 6.1 on 2026-09-06 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Digits only.', max_length=20)),
                ('direction', models.CharField(choices=[('in', 'From the member'), ('out', 'To the member')], max_length=3)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('received', 'Received')], default='queued', max_length=10)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('is_automated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='messaging_m_phone_b2f6b7_idx')],
            },
        ),
    ]
