# Generated by Django 6.1 on 2026-09-07 10:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0003_checkinout_day_pass_alter_checkinout_user_and_more'),
        ('pt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('question', models.CharField(default='How likely are you to recommend us to a friend?', help_text='Shown above the 0-10 scale.', max_length=200)),
                ('trigger', models.CharField(choices=[('post_checkin', 'After a visit'), ('post_pt', 'After a personal training session'), ('manual', 'Any time')], default='manual', max_length=12)),
                ('cooldown_days', models.PositiveSmallIntegerField(default=90, help_text='Leave a member alone for this long after they answer.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('trigger',), name='one_active_survey_per_trigger')],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='0 to 10.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('pt_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='pt.ptsession')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.survey')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='attendance.checkinout')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['survey', 'created_at'], name='feedback_su_survey__3f1b3f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 10)), name='survey_score_is_zero_to_ten'), models.UniqueConstraint(condition=models.Q(('visit__isnull', False)), fields=('survey', 'visit'), name='one_response_per_visit'), models.UniqueConstraint(condition=models.Q(('pt_session__isnull', False)), fields=('survey', 'pt_session'), name='one_response_per_pt_session')],
            },
        ),
    ]
