# Generated by Django 6.1 on 2026-09-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_survey_organisation_surveyresponse_tenant'),
        ('tenancy', '0002_backfill_the_founding_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='survey',
            name='one_active_survey_per_trigger',
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organisation', 'trigger'), name='one_active_survey_per_trigger_per_organisation'),
        ),
    ]
