# Generated by Django 6.1 on 2026-09-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_survey_one_active_survey_per_trigger_and_more'),
        ('tenancy', '0003_backfill_training_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.organisation'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
    ]
