# Generated by Django 6.1 on 2026-09-08 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Stable id used in URLs and support tooling.', max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Appears in /t/<slug>/ and later maps to a custom domain.', max_length=60, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('invoice_prefix', models.CharField(blank=True, help_text='Prefixes invoice numbers, e.g. FIT in FIT/2025-26/0001.', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenancy.organisation')),
            ],
            options={
                'ordering': ['organisation__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('trainer', 'Trainer'), ('admin', 'Admin')], max_length=10)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['tenant', 'user', 'role'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='tenancy_mem_user_id_4a284b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant', 'role'), name='one_membership_per_user_tenant_role'), models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('expires_on__gte', models.F('starts_on')), _connector='OR'), name='membership_does_not_expire_before_it_starts')],
            },
        ),
    ]
