# Generated by Django 6.1 on 2026-09-08 16:36

import django.db.models.deletion
import tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_sweep_stragglers_before_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('verification_token', models.CharField(default=tenancy.models._new_verification_token, editable=False, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('certificate', models.CharField(choices=[('pending', 'Not requested yet'), ('issuing', 'Host is issuing'), ('active', 'Live'), ('failed', 'Failed - see the host')], default='pending', max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-is_primary', 'hostname'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant',), name='one_primary_domain_per_tenant')],
            },
        ),
    ]
