# Generated by Django 6.1 on 2026-09-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253)),
                ('from_local_part', models.CharField(default='no-reply', max_length=64)),
                ('from_name', models.CharField(blank=True, help_text="The name beside the address. Defaults to the gym's name.", max_length=80)),
                ('dkim_selector', models.CharField(blank=True, max_length=64)),
                ('dkim_value', models.TextField(blank=True)),
                ('return_path_cname', models.CharField(blank=True, max_length=253)),
                ('spf_verified', models.BooleanField(default=False)),
                ('dkim_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sending_domain', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
