# Generated by Django 6.1 on 2026-09-08 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_sendingdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Where this key is used.', max_length=80)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('allowed_origins', models.TextField(blank=True, help_text='One origin per line, e.g. https://www.yourgym.com')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('leads_created', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_keys', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
