# Generated by Django 6.1 on 2026-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_leadapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadapikey',
            name='failures_since_success',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadapikey',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadapikey',
            name='last_failure_reason',
            field=models.CharField(blank=True, choices=[('revoked', 'The key has been revoked'), ('origin', 'Blocked by the allowed-addresses list'), ('suspended', 'The gym is not accepting enquiries'), ('payload', 'The form did not send a name and contact'), ('rate', 'Too many submissions in one hour')], max_length=20),
        ),
    ]
